version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: query_logs
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build: ./app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://user:password@db/query_logs
      - FLASK_ENV=development

volumes:
  db-data:
