name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: pip install -r requirements.txt
    
    - name: Run tests
      run: pytest
    
    - name: Lint code
      run: pylint app

    - name: Build Docker image
      run: docker build -t your-dockerhub-repo/your-app:0.1.0 .

    - name: Push Docker image
      run: docker push your-dockerhub-repo/your-app:0.1.0
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Package Helm chart
      run: helm package helm-chart/
